lang: en_US  # en_US for English, ru_RU для русского языка

limits:
  enabled: false
  # for the "on" type — true, for the "off" type — false
  # для выключения пишите - true, для выключения - false

  max-legendary-weapons: 4
  # the maximum number of weapons a player can carry in their inventory
  # максимум оружий которые игрок может носить в инвентаре

  max-copper-armor: 2
  # maximum wearable copper armor
  # максимум ношения медной брони

  # Legendary weapons are now stored in `weapons.yml`.
  # Конфиг лег теперь в weapons.yml

# Player heads drop on death / Выпадение голов игроков при смерти
player-heads:
  enabled: true
